/**
 * This class was generated by MyBatis Generator, do not modify.
 *
 * @Filename PPayDO.java
 *
 * @Author ychaoyang
 *
 */
package dal.model.platformpay;

import java.io.Serializable;
import java.util.Date;

public class PPayDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.ACCOUNT_ID
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.PAY_NO
     *
     * @mbg.generated
     */
    private String payNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.ORDER_NO
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.TRADE_NO
     *
     * @mbg.generated
     */
    private String tradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.PAY_TYPE
     *
     * @mbg.generated
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.PAY_CHANNEL
     *
     * @mbg.generated
     */
    private String payChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.AMOUNT
     *
     * @mbg.generated
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.SOURCE
     *
     * @mbg.generated
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.FEE
     *
     * @mbg.generated
     */
    private Long fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.notify_url
     *
     * @mbg.generated
     */
    private String notifyUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.REMARK
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.payer
     *
     * @mbg.generated
     */
    private String payer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.CHANNEL_CONFIG_ID
     *
     * @mbg.generated
     */
    private String channelConfigId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.PAY_MAPPING
     *
     * @mbg.generated
     */
    private String payMapping;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.RETURN_DATE
     *
     * @mbg.generated
     */
    private Date returnDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.RETURN_DETAIL
     *
     * @mbg.generated
     */
    private String returnDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.REQUEST_DETAIL
     *
     * @mbg.generated
     */
    private String requestDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.CREATED_DATE
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.MODIFIED_DATE
     *
     * @mbg.generated
     */
    private Date modifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.CREATED_USER
     *
     * @mbg.generated
     */
    private String createdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.UPDATED_USER
     *
     * @mbg.generated
     */
    private String updatedUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.MARK_DELETE
     *
     * @mbg.generated
     */
    private String markDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.FINISH_DATE
     *
     * @mbg.generated
     */
    private Date finishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.CHANNEL_ID
     *
     * @mbg.generated
     */
    private String channelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_pay.VERSION_ID
     *
     * @mbg.generated
     */
    private Long versionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table p_pay
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.ID
     *
     * @return the value of p_pay.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.ID
     *
     * @param id the value for p_pay.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.ACCOUNT_ID
     *
     * @return the value of p_pay.ACCOUNT_ID
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.ACCOUNT_ID
     *
     * @param accountId the value for p_pay.ACCOUNT_ID
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.PAY_NO
     *
     * @return the value of p_pay.PAY_NO
     *
     * @mbg.generated
     */
    public String getPayNo() {
        return payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.PAY_NO
     *
     * @param payNo the value for p_pay.PAY_NO
     *
     * @mbg.generated
     */
    public void setPayNo(String payNo) {
        this.payNo = payNo == null ? null : payNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.ORDER_NO
     *
     * @return the value of p_pay.ORDER_NO
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.ORDER_NO
     *
     * @param orderNo the value for p_pay.ORDER_NO
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.TRADE_NO
     *
     * @return the value of p_pay.TRADE_NO
     *
     * @mbg.generated
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.TRADE_NO
     *
     * @param tradeNo the value for p_pay.TRADE_NO
     *
     * @mbg.generated
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.PAY_TYPE
     *
     * @return the value of p_pay.PAY_TYPE
     *
     * @mbg.generated
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.PAY_TYPE
     *
     * @param payType the value for p_pay.PAY_TYPE
     *
     * @mbg.generated
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.PAY_CHANNEL
     *
     * @return the value of p_pay.PAY_CHANNEL
     *
     * @mbg.generated
     */
    public String getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.PAY_CHANNEL
     *
     * @param payChannel the value for p_pay.PAY_CHANNEL
     *
     * @mbg.generated
     */
    public void setPayChannel(String payChannel) {
        this.payChannel = payChannel == null ? null : payChannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.AMOUNT
     *
     * @return the value of p_pay.AMOUNT
     *
     * @mbg.generated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.AMOUNT
     *
     * @param amount the value for p_pay.AMOUNT
     *
     * @mbg.generated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.STATUS
     *
     * @return the value of p_pay.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.STATUS
     *
     * @param status the value for p_pay.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.SOURCE
     *
     * @return the value of p_pay.SOURCE
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.SOURCE
     *
     * @param source the value for p_pay.SOURCE
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.FEE
     *
     * @return the value of p_pay.FEE
     *
     * @mbg.generated
     */
    public Long getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.FEE
     *
     * @param fee the value for p_pay.FEE
     *
     * @mbg.generated
     */
    public void setFee(Long fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.notify_url
     *
     * @return the value of p_pay.notify_url
     *
     * @mbg.generated
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.notify_url
     *
     * @param notifyUrl the value for p_pay.notify_url
     *
     * @mbg.generated
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.REMARK
     *
     * @return the value of p_pay.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.REMARK
     *
     * @param remark the value for p_pay.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.payer
     *
     * @return the value of p_pay.payer
     *
     * @mbg.generated
     */
    public String getPayer() {
        return payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.payer
     *
     * @param payer the value for p_pay.payer
     *
     * @mbg.generated
     */
    public void setPayer(String payer) {
        this.payer = payer == null ? null : payer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.CHANNEL_CONFIG_ID
     *
     * @return the value of p_pay.CHANNEL_CONFIG_ID
     *
     * @mbg.generated
     */
    public String getChannelConfigId() {
        return channelConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.CHANNEL_CONFIG_ID
     *
     * @param channelConfigId the value for p_pay.CHANNEL_CONFIG_ID
     *
     * @mbg.generated
     */
    public void setChannelConfigId(String channelConfigId) {
        this.channelConfigId = channelConfigId == null ? null : channelConfigId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.PAY_MAPPING
     *
     * @return the value of p_pay.PAY_MAPPING
     *
     * @mbg.generated
     */
    public String getPayMapping() {
        return payMapping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.PAY_MAPPING
     *
     * @param payMapping the value for p_pay.PAY_MAPPING
     *
     * @mbg.generated
     */
    public void setPayMapping(String payMapping) {
        this.payMapping = payMapping == null ? null : payMapping.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.RETURN_DATE
     *
     * @return the value of p_pay.RETURN_DATE
     *
     * @mbg.generated
     */
    public Date getReturnDate() {
        return returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.RETURN_DATE
     *
     * @param returnDate the value for p_pay.RETURN_DATE
     *
     * @mbg.generated
     */
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.RETURN_DETAIL
     *
     * @return the value of p_pay.RETURN_DETAIL
     *
     * @mbg.generated
     */
    public String getReturnDetail() {
        return returnDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.RETURN_DETAIL
     *
     * @param returnDetail the value for p_pay.RETURN_DETAIL
     *
     * @mbg.generated
     */
    public void setReturnDetail(String returnDetail) {
        this.returnDetail = returnDetail == null ? null : returnDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.REQUEST_DETAIL
     *
     * @return the value of p_pay.REQUEST_DETAIL
     *
     * @mbg.generated
     */
    public String getRequestDetail() {
        return requestDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.REQUEST_DETAIL
     *
     * @param requestDetail the value for p_pay.REQUEST_DETAIL
     *
     * @mbg.generated
     */
    public void setRequestDetail(String requestDetail) {
        this.requestDetail = requestDetail == null ? null : requestDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.CREATED_DATE
     *
     * @return the value of p_pay.CREATED_DATE
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.CREATED_DATE
     *
     * @param createdDate the value for p_pay.CREATED_DATE
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.MODIFIED_DATE
     *
     * @return the value of p_pay.MODIFIED_DATE
     *
     * @mbg.generated
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.MODIFIED_DATE
     *
     * @param modifiedDate the value for p_pay.MODIFIED_DATE
     *
     * @mbg.generated
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.CREATED_USER
     *
     * @return the value of p_pay.CREATED_USER
     *
     * @mbg.generated
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.CREATED_USER
     *
     * @param createdUser the value for p_pay.CREATED_USER
     *
     * @mbg.generated
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser == null ? null : createdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.UPDATED_USER
     *
     * @return the value of p_pay.UPDATED_USER
     *
     * @mbg.generated
     */
    public String getUpdatedUser() {
        return updatedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.UPDATED_USER
     *
     * @param updatedUser the value for p_pay.UPDATED_USER
     *
     * @mbg.generated
     */
    public void setUpdatedUser(String updatedUser) {
        this.updatedUser = updatedUser == null ? null : updatedUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.MARK_DELETE
     *
     * @return the value of p_pay.MARK_DELETE
     *
     * @mbg.generated
     */
    public String getMarkDelete() {
        return markDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.MARK_DELETE
     *
     * @param markDelete the value for p_pay.MARK_DELETE
     *
     * @mbg.generated
     */
    public void setMarkDelete(String markDelete) {
        this.markDelete = markDelete == null ? null : markDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.FINISH_DATE
     *
     * @return the value of p_pay.FINISH_DATE
     *
     * @mbg.generated
     */
    public Date getFinishDate() {
        return finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.FINISH_DATE
     *
     * @param finishDate the value for p_pay.FINISH_DATE
     *
     * @mbg.generated
     */
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.CHANNEL_ID
     *
     * @return the value of p_pay.CHANNEL_ID
     *
     * @mbg.generated
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.CHANNEL_ID
     *
     * @param channelId the value for p_pay.CHANNEL_ID
     *
     * @mbg.generated
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_pay.VERSION_ID
     *
     * @return the value of p_pay.VERSION_ID
     *
     * @mbg.generated
     */
    public Long getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_pay.VERSION_ID
     *
     * @param versionId the value for p_pay.VERSION_ID
     *
     * @mbg.generated
     */
    public void setVersionId(Long versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_pay
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append(", id=").append(id);
        sb.append(", accountId=").append(accountId);
        sb.append(", payNo=").append(payNo);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", tradeNo=").append(tradeNo);
        sb.append(", payType=").append(payType);
        sb.append(", payChannel=").append(payChannel);
        sb.append(", amount=").append(amount);
        sb.append(", status=").append(status);
        sb.append(", source=").append(source);
        sb.append(", fee=").append(fee);
        sb.append(", notifyUrl=").append(notifyUrl);
        sb.append(", remark=").append(remark);
        sb.append(", payer=").append(payer);
        sb.append(", channelConfigId=").append(channelConfigId);
        sb.append(", payMapping=").append(payMapping);
        sb.append(", returnDate=").append(returnDate);
        sb.append(", returnDetail=").append(returnDetail);
        sb.append(", requestDetail=").append(requestDetail);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", modifiedDate=").append(modifiedDate);
        sb.append(", createdUser=").append(createdUser);
        sb.append(", updatedUser=").append(updatedUser);
        sb.append(", markDelete=").append(markDelete);
        sb.append(", finishDate=").append(finishDate);
        sb.append(", channelId=").append(channelId);
        sb.append(", versionId=").append(versionId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_pay
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PPayDO other = (PPayDO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAccountId() == null ? other.getAccountId() == null : this.getAccountId().equals(other.getAccountId()))
            && (this.getPayNo() == null ? other.getPayNo() == null : this.getPayNo().equals(other.getPayNo()))
            && (this.getOrderNo() == null ? other.getOrderNo() == null : this.getOrderNo().equals(other.getOrderNo()))
            && (this.getTradeNo() == null ? other.getTradeNo() == null : this.getTradeNo().equals(other.getTradeNo()))
            && (this.getPayType() == null ? other.getPayType() == null : this.getPayType().equals(other.getPayType()))
            && (this.getPayChannel() == null ? other.getPayChannel() == null : this.getPayChannel().equals(other.getPayChannel()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()))
            && (this.getFee() == null ? other.getFee() == null : this.getFee().equals(other.getFee()))
            && (this.getNotifyUrl() == null ? other.getNotifyUrl() == null : this.getNotifyUrl().equals(other.getNotifyUrl()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getPayer() == null ? other.getPayer() == null : this.getPayer().equals(other.getPayer()))
            && (this.getChannelConfigId() == null ? other.getChannelConfigId() == null : this.getChannelConfigId().equals(other.getChannelConfigId()))
            && (this.getPayMapping() == null ? other.getPayMapping() == null : this.getPayMapping().equals(other.getPayMapping()))
            && (this.getReturnDate() == null ? other.getReturnDate() == null : this.getReturnDate().equals(other.getReturnDate()))
            && (this.getReturnDetail() == null ? other.getReturnDetail() == null : this.getReturnDetail().equals(other.getReturnDetail()))
            && (this.getRequestDetail() == null ? other.getRequestDetail() == null : this.getRequestDetail().equals(other.getRequestDetail()))
            && (this.getCreatedDate() == null ? other.getCreatedDate() == null : this.getCreatedDate().equals(other.getCreatedDate()))
            && (this.getModifiedDate() == null ? other.getModifiedDate() == null : this.getModifiedDate().equals(other.getModifiedDate()))
            && (this.getCreatedUser() == null ? other.getCreatedUser() == null : this.getCreatedUser().equals(other.getCreatedUser()))
            && (this.getUpdatedUser() == null ? other.getUpdatedUser() == null : this.getUpdatedUser().equals(other.getUpdatedUser()))
            && (this.getMarkDelete() == null ? other.getMarkDelete() == null : this.getMarkDelete().equals(other.getMarkDelete()))
            && (this.getFinishDate() == null ? other.getFinishDate() == null : this.getFinishDate().equals(other.getFinishDate()))
            && (this.getChannelId() == null ? other.getChannelId() == null : this.getChannelId().equals(other.getChannelId()))
            && (this.getVersionId() == null ? other.getVersionId() == null : this.getVersionId().equals(other.getVersionId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_pay
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAccountId() == null) ? 0 : getAccountId().hashCode());
        result = prime * result + ((getPayNo() == null) ? 0 : getPayNo().hashCode());
        result = prime * result + ((getOrderNo() == null) ? 0 : getOrderNo().hashCode());
        result = prime * result + ((getTradeNo() == null) ? 0 : getTradeNo().hashCode());
        result = prime * result + ((getPayType() == null) ? 0 : getPayType().hashCode());
        result = prime * result + ((getPayChannel() == null) ? 0 : getPayChannel().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
        result = prime * result + ((getFee() == null) ? 0 : getFee().hashCode());
        result = prime * result + ((getNotifyUrl() == null) ? 0 : getNotifyUrl().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getPayer() == null) ? 0 : getPayer().hashCode());
        result = prime * result + ((getChannelConfigId() == null) ? 0 : getChannelConfigId().hashCode());
        result = prime * result + ((getPayMapping() == null) ? 0 : getPayMapping().hashCode());
        result = prime * result + ((getReturnDate() == null) ? 0 : getReturnDate().hashCode());
        result = prime * result + ((getReturnDetail() == null) ? 0 : getReturnDetail().hashCode());
        result = prime * result + ((getRequestDetail() == null) ? 0 : getRequestDetail().hashCode());
        result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
        result = prime * result + ((getModifiedDate() == null) ? 0 : getModifiedDate().hashCode());
        result = prime * result + ((getCreatedUser() == null) ? 0 : getCreatedUser().hashCode());
        result = prime * result + ((getUpdatedUser() == null) ? 0 : getUpdatedUser().hashCode());
        result = prime * result + ((getMarkDelete() == null) ? 0 : getMarkDelete().hashCode());
        result = prime * result + ((getFinishDate() == null) ? 0 : getFinishDate().hashCode());
        result = prime * result + ((getChannelId() == null) ? 0 : getChannelId().hashCode());
        result = prime * result + ((getVersionId() == null) ? 0 : getVersionId().hashCode());
        return result;
    }
}